/**
 * Types shared across all three processes (main, preload, renderer).
 *
 * This file is the contract. If a shape crosses a process boundary it belongs
 * here, so that the main process and the React app can never drift apart on
 * what a message looks like.
 *
 * The field names mirror the JSON the Python sidecar emits, so there is no
 * silent renaming layer between the parser and the UI.
 */

/** Read-only facts about the host, resolved once at startup. */
export interface HostInfo {
  platform: NodeJS.Platform
  appVersion: string
  electronVersion: string
}

// --- Parsing ---------------------------------------------------------------

/**
 * Which pipeline the sidecar used for a document.
 * `text` means the PDF had a usable text layer; `ocr` means it was scanned.
 */
export type ExtractionPath = 'text' | 'ocr'

/**
 * Phases a parse moves through. The sidecar also sends the display string, so
 * this is for logic (choosing an icon, deciding what is skippable) rather than
 * for building the message.
 */
export type ParsePhase =
  | 'opening'
  | 'reading'
  | 'structure'
  | 'ocr_switch'
  | 'ocr'
  | 'stalled'
  | 'direction'
  | 'finishing'

export interface ParseProgress {
  /** Correlates this event with the `parsePdf` call that produced it. */
  requestId: string
  phase: ParsePhase
  /** Ready-to-display text. Wording is owned by the sidecar, not the UI. */
  message: string
  percent: number
  /**
   * Whether RTL content was actually found in *this* document.
   *
   * The "Fixing text direction" status line must only ever be shown when this
   * is true - showing it unconditionally would be a lie on Latin documents.
   */
  hasRtlContent: boolean
  current?: number
  total?: number
}

export interface ParsePdfRequest {
  /** Generated by the caller so progress and cancellation can address it. */
  requestId: string
  path: string
  /** Overrides the auto-detected Tesseract location. */
  tesseractPath?: string
  /** Tesseract language packs, e.g. "fas+eng". */
  ocrLanguages?: string
}

export interface ParseResult {
  markdown: string
  pageCount: number
  hasRtl: boolean
  pathUsed: ExtractionPath
  /** How many reversed runs the RTL repair actually corrected. */
  wordsReversed: number
}

/** A failure that reached the user rather than crashing the sidecar. */
export interface ParseError {
  message: string
  /** Where it went wrong, so the UI can point at the file or the settings. */
  phase: string
}

export interface OcrInfo {
  available: boolean
  path?: string
  languages: string[]
  /** Present when `available` is false: why it could not be found. */
  reason?: string
}

// --- Files -----------------------------------------------------------------

export interface MarkdownDocument {
  /** Absolute path, or null for a document that has never been saved. */
  path: string | null
  content: string
}

/** An entry in the welcome screen's recent list. */
export interface RecentFile {
  path: string
  /** Basename, precomputed so the renderer never has to parse a path. */
  name: string
  kind: 'pdf' | 'markdown'
  /** ISO timestamp of the most recent open. */
  openedAt: string
}

// --- The renderer's whole view of the outside world ------------------------

/**
 * The complete surface the renderer can reach, exposed on `window.api` by the
 * preload script. Nothing else in Electron or Node is reachable from React.
 */
export interface DocflowApi {
  getHostInfo: () => Promise<HostInfo>

  /** Parse a PDF to markdown. Rejects with a `ParseError`-shaped reason. */
  parsePdf: (request: ParsePdfRequest) => Promise<ParseResult>
  /**
   * Abandon an in-flight parse.
   *
   * The sidecar processes one request synchronously, so this restarts the
   * process rather than asking it politely to stop - see sidecar.ts.
   */
  cancelParse: (requestId: string) => Promise<void>
  /** Subscribe to progress events. Returns an unsubscribe function. */
  onParseProgress: (listener: (progress: ParseProgress) => void) => () => void

  /** Whether OCR is usable on this machine, and with which languages. */
  getOcrInfo: (tesseractPath?: string) => Promise<OcrInfo>

  /** Show the native picker. Returns [] if the user cancelled. */
  openPdfDialog: () => Promise<string[]>
  readMarkdown: (path: string) => Promise<string>
  writeMarkdown: (path: string, content: string) => Promise<void>
  /** Show a save dialog. Returns null if the user cancelled. */
  saveMarkdownDialog: (suggestedName: string) => Promise<string | null>

  getRecentFiles: () => Promise<RecentFile[]>
  /** Records an open and returns the updated list. */
  addRecentFile: (path: string, kind: RecentFile['kind']) => Promise<RecentFile[]>
  clearRecentFiles: () => Promise<RecentFile[]>

  /**
   * Resolve the absolute path of a dropped File.
   *
   * Electron removed the non-standard `File.path` property, so a drag-and-drop
   * handler in the renderer cannot learn where the file actually is. This is
   * the supported replacement and it must run in the preload context.
   */
  getPathForFile: (file: File) => string
}
